name: agendaku
description: "Agendaku - To Do List Management System dengan Flutter dan Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.5.0
  
  # State Management
  provider: ^6.0.0
  
  # Image Picker
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # UI
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  uuid: ^4.0.0
  
  # Cupertino Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true